### ISSUE TITLE
Back | CameraConf

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/frdm-server#2]
# CameraConfig

- [x] contains conf parameters (in public fields) for [Camera](https://github.com/a-givertzman/frdm-server/issues/3) class
   - [x] fps: size - frames per second 
   - [x] resolution: `CameraResolution`
- [x] creates from 
   - [x] yaml file or 
   - [x] string

[use as example](https://github.com/a-givertzman/cma-server/blob/master/src/conf/slmp_client_config/slmp_client_config.rs)

**Config example:**
```yaml
Camera:
  fps: 30
  addres: 192.168.10.12:2020
  resolution: 
    width: 1200
    height: 800
  ```
